### ISSUE TITLE
Support 32bit systems

### ISSUE THREAD

**Issue by simonschaufi** [fabianmichael/kirby-imageset#11]
Hi, your library sadly only words on 64bit systems.

The reason is this:

https://github.com/fabianmichael/kirby-imageset/blob/master/lib/imageset.php#L414

$hash = hexdec(substr(md5($hash), 0, 15));

in my case the $hash is: 2.8639272122094E+17

generating the hash with this number will crash here:

https://github.com/fabianmichael/kirby-imageset/blob/master/lib/utils.php#L323

where $r is a negative number in my case: -58

and a negative index in an array is not possible.

**Comment by fabianmichael** [comment]
Thanks for pointing this out!

Do you have an idea how to work around this on 32 bit systems?

**Comment by simonschaufi** [comment]
a dirty hack would be to use abs() or use a "proper" hashing method ;) Why so complicated with hexdec and base 16?

**Comment by fabianmichael** [comment]
The hash is actually encoded in base62 (like base64, but without "/" and "="). The sole reason for this is, that hashes are much shorter while keeping a good entropy. However, it cannot stay like this, so I’ll try to find a solution as soon as possible. This will probably take a few days, as my schedule does not leave much room for this week.

**Comment by simonschaufi** [comment]
md5 is a hash which could be used (or a substring of it) and you are already making use of it but still I wonder why you do an extra hexdec and the other stuff...

**Comment by fabianmichael** [comment]
md5 uses only a-f0-9 as characters. My hash function uses a-zA-Z0-9. The reason is just to get shorter hashes, which do not waste bytes and look more readable on the other hand.

I’ll make a branch with a fixed hash function soon, so you can test on your 32 bit system (setting up a VM would take to long just for this sole issue). If you can confirm that it works, I’ll integrate that into master. Does this sound good for you?

**Comment by simonschaufi** [comment]
sounds great!

**Comment by fabianmichael** [comment]
Hey @simonschaufi, I’m going on vacation for the rest of the week and couldn’t manage to fix that bug before. But be sure that I did not forget about it. Will take care of that when I’m back at the desk.

**Comment by fabianmichael** [comment]
Hey @simonschaufi, I finally decided to use md5 hashes instead of base62, as there does not seem to be an easy soluation that’s available on all PHP installations. Updates code is in the repo (master branch), but not part of an official release yet, though tested it on my local (64 bit) machine and it worked fine. Please try if it also work for you, then I’ll tag it as an official release.

**Comment by simonschaufi** [comment]
Great! Unfortunatelly my good old 32 bit windows gave up a few weeks ago with a hardware damage and so I can't test right now but from my point of view it should work.
