### ISSUE TITLE
suggestion: colorthief alternative

### ISSUE THREAD

**Issue by bnomei** [fabianmichael/kirby-imageset#12]
maybe test this lib if its faster, more stable etc.

https://github.com/thephpleague/color-extractor

**Comment by fabianmichael** [comment]
I already tried that one, but performance and memory usage also do not seem to be very good. Still thinking of better ways of how to handle this, but the main issue remains the same for all of those libs: They have to load the whole image into memory and analyse a whole lot of pixels. Same problem I also got for testing whether an image has an alpha channel or not (takes painfully long on the server, but speeds up placeholder rendering in the frontend a lot). For larger images, I already started to create temporary thumbnails, because it reduces memory usage dramatically. Largest speed bump would be possible by creating the temporary thumbnail faster.

Only solution I stumbled upon: [VIPS](http://www.vips.ecs.soton.ac.uk/index.php?title=VIPS) would allows way faster image processing from the command-line, than imagemagick or GD, but is an extra tool a user has to install on his/her server in order to make it work. Not sure yet, if it’s worth the effort …

**Comment by bnomei** [comment]
my usual setup is photos directly from camera and clients perfer color preview over blured image. but thier servers (about 10€/month) are not fast/memory strong enogh to handle color extraction from raw file. 
you mentioned using a thumb for detection instead of raw file. that would be great. is there a setting to define its max width/scale yet?
i have a lot of image focused projects lately so looking into vibs might be worth it. i will check if i can install it on a current project and report back.

**Comment by fabianmichael** [comment]
I got an experimental (untested VIPS) driver for Kirby, wanna try it?

**Comment by bnomei** [comment]
sure. but i can not do any testing before 17.7.

**Comment by bnomei** [comment]
can do testing now. where do i find your VIPS driver?

**Comment by fabianmichael** [comment]
Here it is. But please be careful, I just wrote that down without testing it a single time. The driver installs as a separate plugin.

[vips.zip](https://github.com/fabianmichael/kirby-imageset/files/1222460/vips.zip)
