### ISSUE TITLE
Using files from /assets

### ISSUE THREAD

**Issue by colourgarden** [fabianmichael/kirby-imageset#4]
HI @fabianmichael. Thanks for your work on this great plugin.

I'm trying to create a srcset from an image that I have stored in my /assets folder but am having some trouble. I'm trying the global function as well as the File object method but get the following errors.

```
$image = new Media ($kirby->roots()->assets() . '/images/image.png');
$image->imageset('200');

Call to undefined method Media::imageset()
```

```
$image = new Media ($kirby->roots()->assets() . '/images/ISOW-video-holder.png');
imageset($image, '200');

Class 'Kirby\Plugins\ImageSet\url' not found
```

It may be that I have an incorrect understanding of the Media object but are you able to shed some light on accessing images from /assets?

Thanks!

**Comment by fabianmichael** [comment]
Hi @colourgarden,

this is clearly a bug. Thanks for pointing this out, I’ve just fixed this on the master branch. I’ll leave this open, so you have a chance to test if the fix works for you as well.

Explanation: Instances of the `Media` objects are missing some methods, which are preset on the `Asset` or `File` classes. You can always use the `Asset` class instead of media when access, because it works with relative paths, which is way easier to write:
```php
$image = new Asset('assets/images/image.png');
echo imageset($image, 'default');
```

**Comment by colourgarden** [comment]
Thanks @fabianmichael. Seems to be working now. This is a really great plugin, thanks for your work on it.
