### ISSUE TITLE
Setting options with variables

### ISSUE THREAD

**Issue by colourgarden** [fabianmichael/kirby-imageset#5]
Hi again @fabianmichael. I'm trying to dynamically add a caption using Imageset options but am running into an error. I expect it to work but no dice.

Image is being created with the following code (caption has definitely been set in Panel) with an error returned.

```
$image = $page->image($data->image());
$image_options = ['alt' => $image->caption(), 'placeholder' => 'blurred'];
echo imageset($image, '400, 500, 800, 1024', $image_options);

Uncaught exception 'Exception' with message 'Serialization of 'Closure' is not allowed
```

If I set a blank caption or an ordinary string (instead of `$image->caption()`) then it produces the Imageset image perfectly.

Thanks

**Comment by fabianmichael** [comment]
Hey @colourgarden, this was expected behavior, as imagesets are always cached the unique hash for each image is generated from a serialized string of all options and sizes. But I admit, that it should work with Kirby’s native objects as parameters. Fixed it, so fields are converted to strings before the hash is generated.

Thanks for you feedback so far, it is very helpful! :-) I you find anything else that annoys you, please let me know.
