### ISSUE TITLE
Generate HiDPI images

### ISSUE THREAD

**Issue by Flobin** [fabianmichael/kirby-imageset#9]
Just an idea: are you planning to also generate HiDPI images?

Congrats on all the work so far, by the way, the plugin looks great!

**Comment by fabianmichael** [comment]
Hey @Flobin,

this was my first approach, but for content images which arre usually displayed a lot on different screen sizes, using `1x`, `2x` etc. requires you to know the exact dimensions of images certain screen sizes. When working with a responsive grid, this can become very tricky. When using width descriptors (like ImageSet) currently does, this get’s a lot easier, it’s sufficient for most use-cases to estimate image sizes and provide an array of different sizes. When using ImageSet with the lazy-loading option, the plugin does the rest for you. You can still images at larger resolutions for HiDPI screens.

Example:
> You got a content area which is 1000px wide on large screens. Most of you visitors are equipped with pixel ratios of `1` (most desktop/laptop computers), `1.5` (some Android and Windows devices) and `2` (MacBook Pros, iPhones, Android). You should consider to generate thumbnails at a width 1000, 1500 and 2000 pixels, so every of those devices can be served the right image size. I know, there are also devices with a pixel-ratio of `3x` or higher (iPhone 6+ and some Android devices), but most of these should get get a decent result being served the `2x` version (also keep in mind the costs of generating, storing and serving images at such high resolutions). 

However, there is a way out of serving images at extremely high-resolution: You can drastically reduce the image quality when saving in JPEG format for `2x` resolutions and above, so even images at resolutions of 4000x3000 pixels won’t result in bandwidth problems. But like I already pointed out, I went for the width descriptor solution as it makes things a lot easier to implement and solves lot of problems for real-world usage.

Maybe the possibility of using density descriptors instead of width descriptors will be added in the future, but I’m not sure if it really helps in most situations, cause you’re very likely to end up in much more complex template code. I played around with that and I’m still using it on my personal website, but the way to implementing it like this felt kinda over-engineered. First, I had to do a lot of tests regarding the right compression ratio for retina-images to get to a good compromise between download size and visual quality. Then, I had to figure out the exact dimensions of each image within the grid and possibly nested grid elements. To solve this, I re-built the CSS grid from the frontend in PHP to calculate the exact sizes of each grid item serverside. It works and looks great, but the effort to achieve that was IMHO not worth the result and is not very maintainable. Evertime you’re making changes to a grid in CSS, you have to adjust the PHP counterpart, which is very time-intense and also very error-prone if you’re not a Math Magician (I’m not). Because of these experiences I made, I decided to prefer width descriptors over density descriptors, as the intention if ImageSet is to provide an easy solution to a complex problem, not the other way round.

Maybe do you have a different use-case for HiDPI images usng density descriptors?

**Comment by fabianmichael** [comment]
Closing this, as there seems to be no further need for discussion.
